### ISSUE TITLE
feat: Angular 2 Material Integration

### ISSUE THREAD

**Issue by tapas4java** [rolandjitsu/ng2-lab#2]
It would be great to have Angular2 Material support out of the box.

**Comment by vasspilka** [comment]
Some Angular material components are here [ng-2 material](https://github.com/angular/angular/tree/master/modules/angular2_material)

**Comment by rolandjitsu** [comment]
@vasspilka I was aware of that, but that's nowhere near something we could use at the moment. And there isn't any official distr for that, you can only pull it from git and I would prefer to have it from npm.

**Comment by rolandjitsu** [comment]
Close with f8e8fa0e97bf8a4dd262da3f58956643692ee7f8
